const FIRST_NAMES = [
	"Aaradhya",
	"Adah",
	"Adhira",
	"Alisha",
	"Amoli",
	"Anaisha",
	"Ananya",
	"Anika",
	"Anushka",
	"Asmee",
	"Avni",
	"Carina",
	"Drishti",
	"Hiya",
	"Ira",
	"Ishana",
	"Ishita",
	"Kaia",
	"Kashvi",
	"Keya",
	"Kimaya",
	"Krisha",
	"Larisa",
	"Mahika",
	"Mayra",
	"Mehar",
	"Mirai",
	"Mishka",
	"Naitee",
	"Navya",
	"Nehrika",
	"Neysa",
	"Pavati",
	"Prisha",
	"Ryka",
	"Rebecca",
	"Saanvi",
	"Sahana",
	"Sai",
	"Saisha",
	"Saloni",
	"Shanaya",
	"Shrishti",
	"Sneha",
	"Taahira",
	"Taara",
	"Tanvi",
	"Viti",
	"Zara",
	"Aahva",
	"Aadiv",
	"Aarav",
	"Akanksh",
	"Alex",
	"Anant",
	"Atiksh",
	"Ayaan",
	"Bhuv",
	"Dasya",
	"Gian",
	"Hem",
	"Idhant",
	"Ishank",
	"Jash",
	"Jay",
	"Joseph",
	"Kabir",
	"Kahaan",
	"Kairav",
	"Kevin",
	"Laksh",
	"Luv",
	"Manan",
	"Mohammad",
	"Naksh",
	"Nimit",
	"Nirav",
	"Pahal",
	"Parv",
	"Pranay",
	"Rachit",
	"Raj",
	"Ranbir",
	"Raunak",
	"Reyansh",
	"Rishaan",
	"Rishit",
	"Rohan",
	"Rudra",
	"Rushil",
	"Sadhil",
	"Sarthak",
	"Taarush",
	"Taksh",
	"Ved",
	"Vihaan",
	"Vivaan",
	"Yash",
	"Yug",
	"Zuber"
];

const LAST_NAMES = [
	"Acharya",
	"Agarwal",
	"Khatri",
	"Ahuja",
	"Anand",
	"Laghari",
	"Patel",
	"Reddy",
	"Bakshi",
	"Anthony",
	"Babu",
	"Arya",
	"Balakrishnan",
	"Banerjee",
	"Burman",
	"Bhatt",
	"Basu",
	"Bedi",
	"Varma",
	"Dara",
	"Dalal",
	"Chowdhury",
	"Chabra",
	"Chadha",
	"Chakrabarti",
	"Chawla",
	"Ahluwalia",
	"Amin",
	"Apte",
	"Datta",
	"Deol",
	"Deshpande",
	"Dewan",
	"Lal",
	"Kohli",
	"Mangal",
	"Malhotra",
	"Jha",
	"Joshi",
	"Kapadia",
	"Iyer",
	"Jain",
	"Khanna",
	"Grover",
	"Kaur",
	"Kashyap",
	"Gokhale",
	"Ghosh",
	"Garg",
	"Dhar",
	"Gandhi",
	"Ganguly",
	"Gupta",
	"Das",
	"Chopra",
	"Dhawan",
	"Dixit",
	"Dubey",
	"Haldar",
	"Kapoor",
	"Khurana",
	"Kulkarni",
	"Madan",
	"Bajwa",
	"Bhasin",
	"Chandra",
	"Chauhan",
	"Deshmukh",
	"Dayal",
	"Dhillon",
	"Goswami",
	"Goel",
	"Mallick",
	"Mahajan",
	"Kumar",
	"Mani",
	"Gill",
	"Mannan",
	"Biswas",
	"Batra",
	"Bawa",
	"Mehta",
	"Mukherjee",
	"Saxena",
	"Zacharia",
	"Shah",
	"Ray",
	"Rao",
	"Purohit",
	"Parekh",
	"Thakur",
	"Singh",
	"Sharma",
	"Seth",
	"Sachdev",
	"Ranganathan",
	"Puri",
	"Pandey",
	"Naidu",
	"Modi"
];

const SPECIALIZATIONS = [
	"Orthopaedist",
	"Cardiologist",
	"Dermatologist",
	"Ophthalmologist",
	"General Practitioner",
	"Gynaecologist"
];

const HOSPITALS = [
	"Asian Heart Institute, Bandra-Kurla Complex",
	"Bhabha Hospital, Bandra",
	"Bhaktivedanta Hospital, Mira Road",
	"Bombay Hospital, Marine Lines",
	"Breach Candy Hospital, Mahalaxmi",
	"D Y Patil Hospital, Nerul",
	"Cloudnine Hospitals, Link Road, Malad West",
	"Cooper Hospital, Vile Parle",
	"Gokuldas Tejpal Hospital, Fort",
	"Grant Medical College and Sir Jamshedjee Jeejebhoy Group of Hospitals, Sandhurst Road",
	"Hinduja Hospital, Mumbai",
	"Holy Family Hospital, Bandra",
	"Hurkisondas Hospital, Girgaon",
	"Jaslok Hospital, Pedar Road",
	"Lilavati Hospital, Bandra",
	"Lokmanya Tilak Hospital, Sion",
	"Nanavati Hospital, Vile Parle",
	"Prince Aly Khan Hospital, Byculla",
	"Rajawadi Hospital, Ghatkopar",
	"Saifee Hospital, Charni Road",
	"KEM Hospital, Parel",
	"Shushrusha Citizens' Co-operative Hospital, Shivaji Park, Mumbai",
	"Sunrise Hospital, Bhandup",
	"Tata Memorial Hospital, Parel",
	"Mahatma Gandhi Memorial Hospital, Parel"
];

function createDoctors(n){
	let a = [];
	for(let i = 0; i < n; i++)
		a[i] = createDoctor();
	
	return a;
}

function createDoctor(){
	return {
		name: getRandomElement(FIRST_NAMES) + " " + getRandomElement(LAST_NAMES),
		specialization: getRandomElement(SPECIALIZATIONS),
		hospital: getRandomElement(HOSPITALS)
	};
}

function getRandomElement(a){
	return a[Math.floor((a.length) * Math.random())];
}